module.exports = {
	darkMode: "class",
	content: ["src/**/*.{ts,html,css,scss,svelte}"],
	theme: {
		extend: {
			colors: {
				fg: {
					default: "#24292E",
					muted: "#57606A",
					subtle: "#6E7781",
					onEmphasis: "#FFFFFF",
					accent: "#0968DA",
					success: "#1B7F36",
					attention: "#9A6700",
					danger: "#CF212E",
					severe: "#BC4C00",
					open: "#1B7F36",
					closed: "#CF212E",
					done: "#824FDE",
				},
				bg: {
					emphasis: "#24292E",
					default: "#FFFFFF",
					subtle: "#F5F8FA",
					inset: "#F5F8FA",
					accent: "#DCF3FF",
					success: "#D9FBE1",
					attention: "#FFF8C4",
					danger: "#FFEBE9",
					severe: "#FFF0E4",
					open: "#D9FBE1",
					closed: "#FFEBE9",
					done: "#FBEEFF",
					emphasisHighlighted: "#0968DA",
				},
				border: {
					default: "#CFD7DD",
					muted: "#D8DEE3",
					accent: "#BDDFFF",
					success: "#BCE7C4",
					attention: "#EEDCB0",
					danger: "#FFCDCD",
					severe: "#FFD2B7",
					open: "#BCE7C4",
					close: "#FFCDCD",
					done: "#E7D5FF",
					emphasisHighlighted: "#0968DA",
				},
			},
		},
	},
	plugins: [],
};
