module.exports = {
	darkMode: "class",
	content: ["src/**/*.{ts,tsx,html,css,scss,svelte}"],
	safelist: [
		// Foreground colors
		"text-fg-default",
		"text-fg-muted",
		"text-fg-subtle",
		"text-fg-onEmphasis",
		"text-fg-accent",
		"text-fg-success",
		"text-fg-attention",
		"text-fg-danger",
		"text-fg-severe",
		"text-fg-open",
		"text-fg-closed",
		"text-fg-done",
		// Background colors
		"text-bg-emphasis",
		"text-bg-default",
		"text-bg-subtle",
		"text-bg-inset",
		"text-bg-accent",
		"text-bg-success",
		"text-bg-attention",
		"text-bg-danger",
		"text-bg-severe",
		"text-bg-open",
		"text-bg-closed",
		"text-bg-done",
		"text-bg-highlighted",
		// Border colors
		"text-border-default",
		"text-border-muted",
		"text-border-accent",
		"text-border-success",
		"text-border-attention",
		"text-border-danger",
		"text-border-severe",
		"text-border-open",
		"text-border-close",
		"text-border-done",
		"text-border-highlighted",
	],
	theme: {
		extend: {
			colors: {
				fg: {
					default: "#24292E",
					muted: "#57606A",
					subtle: "#6E7781",
					onEmphasis: "#FFFFFF",
					accent: "#0968DA",
					success: "#1B7F36",
					attention: "#9A6700",
					danger: "#CF212E",
					severe: "#BC4C00",
					open: "#1B7F36",
					closed: "#CF212E",
					done: "#824FDE",
				},
				bg: {
					emphasis: "#24292E",
					default: "#FFFFFF",
					subtle: "#F5F8FA",
					inset: "#F5F8FA",
					accent: "#DCF3FF",
					success: "#D9FBE1",
					attention: "#FFF8C4",
					danger: "#FFEBE9",
					severe: "#FFF0E4",
					open: "#D9FBE1",
					closed: "#FFEBE9",
					done: "#FBEEFF",
					highlighted: "#0968DA",
				},
				border: {
					default: "#CFD7DD",
					muted: "#D8DEE3",
					accent: "#BDDFFF",
					success: "#BCE7C4",
					attention: "#EEDCB0",
					danger: "#FFCDCD",
					severe: "#FFD2B7",
					open: "#BCE7C4",
					close: "#FFCDCD",
					done: "#E7D5FF",
					highlighted: "#0968DA",
				},
			},
		},
	},
	plugins: [],
};
