name: Build and Publish storybook to GitHub Pages

on:
    push:
        branches:
            - "main"
jobs:
    deploy:
        environment:
            name: github-pages
            url: ${{ steps.build-publish.outputs.page_url }}
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install Dependencies
              run: npm install
            - name: Build Project
              run: npm run build
            - id: build-publish
              uses: bitovi/github-actions-storybook-to-github-pages@v1.0.0
              with:
                  path: storybook-static
                  build_command: npm run build-storybook
